name: Manual workflow with Inputs
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose your env"
        required: true
        default: 'development'
        type: choice
        options:
          - 'production'
          - 'development'
          - 'staging'
jobs: 
  deploy:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Print Input
        if: ${{ github.event.inputs.environment == 'production' }}
        run: |
           echo "Environment: ${{github.event.inputs.environment}}  ${{default-branch}}"
      - name: Development
        if: ${{ github.event.inputs.environment == 'production' }}
        run: |
           echo "Environment: ${{github.event.inputs.environment}}"
          
        
